/**
 * Content loader for blog posts, comparison pages, and docs.
 *
 * Posts live in content/blog/*.mdx and are written autonomously by the
 * weekly content engine. We expose helpers to list, fetch by slug, and
 * derive metadata for sitemap / RSS / llms.txt generation.
 */

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

const ROOT = path.join(process.cwd(), "content");

export interface PostFrontmatter {
  title: string;
  slug: string;
  date: string;            // ISO date
  description: string;
  category: "comparison" | "deep-dive" | "case-study" | "doc";
  tags?: string[];
  author?: string;
  ogImage?: string;
  generatedBy?: string;    // "content-engine v1" if autogenerated
}

export interface Post {
  frontmatter: PostFrontmatter;
  content: string;         // raw MDX body
  filepath: string;
}

function safeReadDir(dir: string): string[] {
  try {
    return fs.readdirSync(dir).filter((f) => f.endsWith(".mdx") || f.endsWith(".md"));
  } catch {
    return [];
  }
}

export function listPosts(category?: PostFrontmatter["category"]): Post[] {
  const blogDir = path.join(ROOT, "blog");
  const files = safeReadDir(blogDir);
  const posts = files
    .map((f) => {
      const fp = path.join(blogDir, f);
      const raw = fs.readFileSync(fp, "utf-8");
      const { data, content } = matter(raw);
      const fm = data as PostFrontmatter;
      if (!fm.slug) fm.slug = f.replace(/\.(mdx?|md)$/, "");
      return { frontmatter: fm, content, filepath: fp };
    })
    .filter((p) => !category || p.frontmatter.category === category)
    .sort((a, b) => b.frontmatter.date.localeCompare(a.frontmatter.date));
  return posts;
}

export function getPost(slug: string): Post | null {
  const posts = listPosts();
  return posts.find((p) => p.frontmatter.slug === slug) ?? null;
}

/**
 * Comparison-page metadata. Drives /compare/[competitor].
 * The actual comparison body is rendered by app/compare/[competitor]/page.tsx
 * from this structured data, not from MDX — that keeps the comparison table
 * authoritative and easy to update programmatically.
 */
export const COMPETITORS = [
  {
    slug: "langfuse",
    name: "Langfuse",
    tagline: "LLM engineering platform with traces and evals.",
    differences: [
      "ToolPulse adds schema drift detection on tool responses; Langfuse focuses on prompt traces.",
      "ToolPulse runs synthetic health checks on a schedule; Langfuse is reactive only.",
      "Langfuse is OSS and self-hostable today; ToolPulse self-host is on the roadmap.",
    ],
  },
  {
    slug: "helicone",
    name: "Helicone",
    tagline: "LLM observability via proxy with prompt-level analytics.",
    differences: [
      "Helicone proxies LLM calls; ToolPulse wraps the tool layer one level above.",
      "ToolPulse fingerprints response shapes and alerts on drift — Helicone does not.",
      "ToolPulse is MCP-native; Helicone is OpenAI-style API focused.",
    ],
  },
  {
    slug: "arize-phoenix",
    name: "Arize Phoenix",
    tagline: "OSS LLM observability and tracing.",
    differences: [
      "Phoenix focuses on traces and embeddings drift; ToolPulse focuses on tool reliability.",
      "ToolPulse provides synthetic checks and on-call alerts; Phoenix is investigative.",
    ],
  },
  {
    slug: "agentops",
    name: "AgentOps",
    tagline: "Agent observability with session replay.",
    differences: [
      "Both monitor agent behavior; ToolPulse goes deeper on tool-level shape and drift.",
      "ToolPulse alerts on tool degradation in real time; AgentOps focuses on post-hoc analysis.",
    ],
  },
  {
    slug: "langtrace",
    name: "Langtrace",
    tagline: "OpenTelemetry-based LLM tracing.",
    differences: [
      "Langtrace exports OTel; ToolPulse focuses on tool-call shape integrity.",
      "ToolPulse provides drift-specific alerts that OTel pipelines don't surface natively.",
    ],
  },
] as const;

export function getCompetitor(slug: string) {
  return COMPETITORS.find((c) => c.slug === slug);
}
